version: "3"

services:

  petshop-app:
    container_name: petshop-app
    build: .
    restart: always
    env_file: 
        - .env
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    depends_on: 
        - db
    links:
        - db
    ports: 
      - ${APP_PORT}:3000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    command: npm run start

  db:
    image: mysql:5.7
    container_name: db
    platform: linux/x86_64
    restart: always
    command: --innodb-use-native-aio=0
    env_file: 
        - .env
    ports: 
        - ${DB_PORT}:3306
    tty: true
    volumes: 
      - dbdata-volume:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      #- MYSQL_USER=${DB_USERNAME}
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

#   adminer:
#     image: adminer
#     ports:
#         - 8080:8080
#     extra_hosts:
#         - "host.docker.internal:172.17.0.1"

volumes:
    dbdata-volume: